# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: Test
  dependsOn: [Build]
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
- stage: TestUI
  displayName: Test UI
  dependsOn: [Build]
  jobs:
  - job: TestUIJob
    steps:
    - script: echo Testing UI!
- stage: Deploy
  dependsOn: [Test, TestUI, Build]
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!

